### ISSUE TITLE
regex fails to recognise values containing (quoted) commas

### ISSUE THREAD

**Issue by realshovanshah** [torandu/vim-csv-syntax#1]
Hey, I'm here from the Reddit thread. Thanks for extracting this into a minimal solution (given the apparent lack of one for CSV filetype).

Looks like the initial regex doesn't support more "advanced" cases like the quoted use of commas (`,`). An example:

```csv
name,place,animal
Shyam,home,"cat,dog"
```

In cases such as `"cat,dog"`, as in the last value, quotes are often used to escape the use of commas inside a CSV. 

I'm not sure if this plugin is planned to be maintained for general use (as an alternative csv plugin), but if this is the case, I'd like to propose this as the first fix. Conveniently, [an answer was provided](https://gist.github.com/jakergrossman/cf026270733d68d8abf5c683187e5e8a) in the same [thread](https://www.reddit.com/r/vim/comments/wlelmg/csv_syntax_highlighting/) which seems to solve this specific issue.

**Comment by torandu** [comment]
Resolved with minor colour changes. Thanks!
